### ISSUE TITLE
Show LP per semester

### ISSUE THREAD

**Issue by schmidtflo** [ErikBrendel/onehundredandeighty#6]
Show the LP made in each semester directly (e.g. next to the lock-icon)

**Comment by ErikBrendel** [comment]
Implemented in commit https://github.com/ErikBrendel/onehundredandeighty/commit/b0001be620146dc93c759c01743c087980eb7adb.

**Comment by ErikBrendel** [comment]
Implemented in commit https://github.com/ErikBrendel/onehundredandeighty/commit/b0001be620146dc93c759c01743c087980eb7adb.
