### ISSUE TITLE
3LP + 0.5*6LP = 6LP ?

### ISSUE THREAD

**Issue by ErikBrendel** [ErikBrendel/onehundredandeighty#8]
It seems like one can combine a 3point LV together with half of a 6point LV to get a grade.
 - [ ] Double-check if this is true
 - [ ] Implement it

**Comment by MerlindlH** [comment]
![capture](https://user-images.githubusercontent.com/8302493/37241168-d1f39272-2454-11e8-89e4-e5d981bfbf91.PNG)

another example of this rule: you have 6 LP PEM and 9LP DSchool which makes 15 > 12 LP Softskills which should be possible but currently isn't
Also keep in mind, that this phenomenon only occurs in the 2010 Studienordnung

**Comment by ErikBrendel** [comment]
Official answer:

> in PrüfO 2010: müssen je VG 6LPs aus Vorlesung erworben sein; es können auch 2 mal 3LPs aus Vorlesungen sein.
>  
> In PrüfO 2016: hier gibt es die Vorgabe zur Lehrform „Vorlesung“ nicht.
> Das Modul muss mit mindestens 6LP erfüllt sein. Es ist möglich mehr als 6LP in dieses Modul einzubringen. Alle LPs in diesem Modul werden zur Ermittlung der Modulnote herangezogen/gemittelt.
> Die in dieser Form ermittelte Modulnote hat ein festgelegtes Gewicht von 6, da das Modul die festgelegte Größe von 6 hat  -  auch wenn darin weitere LPs erworben worden sein sollten.
